name: ESLint
on:
  push:
    branches:
      - '*'
      - '!docs'
      - '!develop'
      - '!master'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!docs'
      - '!develop'
      - '!master'
      - '!gh-pages'
jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16']
    name: ESLint (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run TSC
        run: npm run build:check
